-- Migration: Create patent_report table

CREATE TABLE IF NOT EXISTS `patent_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `patent_status` ENUM('filed','published','granted') NOT NULL,
  `position_of_student` INT NULL,
  `is_academic_project` TINYINT(1) DEFAULT 0,
  `faculty_id_1` VARCHAR(50) DEFAULT NULL,
  `faculty_id_2` VARCHAR(50) DEFAULT NULL,
  `faculty_id_3` VARCHAR(50) DEFAULT NULL,
  `faculty_id_4` VARCHAR(50) DEFAULT NULL,
  `registration_date` DATE DEFAULT NULL,
  `application_number` VARCHAR(100) DEFAULT NULL,
  `sdg_goals_id` INT DEFAULT NULL,
  `patent_tracker_id` INT DEFAULT NULL,
  `level` ENUM('national','international') DEFAULT NULL,
  `is_early_publication_filed` TINYINT(1) DEFAULT NULL,
  `is_examination_filed` TINYINT(1) DEFAULT NULL,
  `patent_license_details` TEXT,
  `funding_agency` VARCHAR(255) DEFAULT NULL,
  `funds_received` TINYINT(1) DEFAULT NULL,
  `fund_amount` DECIMAL(12,2) DEFAULT NULL,
  `is_interdisciplinary` TINYINT(1) DEFAULT NULL,
  `other_dept_name` VARCHAR(100) DEFAULT NULL,
  `other_dept_student_count` INT DEFAULT NULL,
  `approve_filed_by_bit_id_publication` INT DEFAULT NULL,
  `approve_filed_by_bit_id_granted` INT DEFAULT NULL,
  `prior_art` TEXT,
  `novelty` TEXT,
  `yukti_proof_url` TEXT,
  `full_document_proof_url` TEXT,
  `cbr_receipt_url` TEXT,
  `publication_proof_url` TEXT,
  `granted_proof_url` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_student` (`student_id`),
  KEY `fk_sdg_goals` (`sdg_goals_id`),
  KEY `fk_faculty_1` (`faculty_id_1`),
  KEY `fk_faculty_2` (`faculty_id_2`),
  KEY `fk_faculty_3` (`faculty_id_3`),
  KEY `fk_faculty_4` (`faculty_id_4`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- NOTE: Add foreign key constraints if your `students`, `faculty` and `sdg_goals` tables exist and match types
