-- Migration: Create patent_report table

CREATE TABLE IF NOT EXISTS `patent_report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `patent_status` ENUM('filed','published','granted') NOT NULL,
  `position_of_student` INT NULL,
  `is_academic_project` TINYINT(1) DEFAULT 0,
  `faculty_id_1` VARCHAR(50) DEFAULT NULL,
  `faculty_id_2` VARCHAR(50) DEFAULT NULL,
  `faculty_id_3` VARCHAR(50) DEFAULT NULL,
  `faculty_id_4` VARCHAR(50) DEFAULT NULL,
  `registration_date` DATE DEFAULT NULL,
  `application_number` VARCHAR(100) DEFAULT NULL,
  `sdg_goals_id` INT DEFAULT NULL,
  `patent_tracker_id` INT DEFAULT NULL,
  `level` ENUM('national','international') DEFAULT NULL,
  `is_early_publication_filed` TINYINT(1) DEFAULT NULL,
  `is_examination_filed` TINYINT(1) DEFAULT NULL,
  `patent_license_details` TEXT,
  `funding_agency` VARCHAR(255) DEFAULT NULL,
  `funds_received` TINYINT(1) DEFAULT NULL,
  `fund_amount` DECIMAL(12,2) DEFAULT NULL,
  `is_interdisciplinary` TINYINT(1) DEFAULT NULL,
  `other_dept_name` VARCHAR(100) DEFAULT NULL,
  `other_dept_student_count` INT DEFAULT NULL,
  `approve_filed_by_bit_id_publication` INT DEFAULT NULL,
  `approve_filed_by_bit_id_granted` INT DEFAULT NULL,
  `yukti_proof_url` TEXT,
  `full_document_proof_url` TEXT,
  `cbr_receipt_url` TEXT,
  `publication_proof_url` TEXT,
  `granted_proof_url` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_student` (`student_id`),
  KEY `fk_sdg_goals` (`sdg_goals_id`),
  KEY `fk_faculty_1` (`faculty_id_1`),
  KEY `fk_faculty_2` (`faculty_id_2`),
  KEY `fk_faculty_3` (`faculty_id_3`),
  KEY `fk_faculty_4` (`faculty_id_4`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- NOTE: Add foreign key constraints if your `students`, `faculty` and `sdg_goals` tables exist and match types





'CREATE TABLE `internship_industries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `industry` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `website_link` varchar(255) DEFAULT NULL,
  `active_now` tinyint(1) DEFAULT ''1'',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001'

'CREATE TABLE `internship_tracker` (
  `id` int NOT NULL AUTO_INCREMENT,
  `student_id` int DEFAULT NULL,
  `industry_id` int DEFAULT NULL,
  `tracker_number` bigint unsigned NOT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `aim_objectives_link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `offer_letter_link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iqac_verification` enum(''initiated'',''approved'',''declined'') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''initiated'',
  `reject_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_1_idx` (`student_id`),
  KEY `fk_2_idx` (`industry_id`),
  CONSTRAINT `fk_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_industry` FOREIGN KEY (`industry_id`) REFERENCES `internship_industries` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=30001'

'CREATE TABLE `internship_reports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tracker_id` int NOT NULL,
  `report_number` bigint unsigned NOT NULL,
  `student_id` int NOT NULL,
  `special_lab_id` int NOT NULL,
  `year_of_study` int NOT NULL,
  `sector` enum(''Government'',''Private'') COLLATE utf8mb4_unicode_ci NOT NULL,
  `industry_address_line_1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `industry_address_line_2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `postal_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `industry_website` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `industry_contact_details` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `referred_by` enum(''Alumni'',''Faculty'',''Others'') COLLATE utf8mb4_unicode_ci NOT NULL,
  `referee_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `referee_mobile_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stipend_received` enum(''Yes'',''No'') COLLATE utf8mb4_unicode_ci NOT NULL,
  `stipend_amount` decimal(10,2) DEFAULT ''0.00'',
  `is_through_aicte` enum(''Yes'',''No'') COLLATE utf8mb4_unicode_ci NOT NULL,
  `claim_type` enum(''Course Exemption'',''Reward Points'') COLLATE utf8mb4_unicode_ci NOT NULL,
  `sdg_goal_id` int NOT NULL,
  `full_document_proof_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_certificate_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attested_certificate_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `iqac_verification` enum(''initiated'',''approved'',''declined'') COLLATE utf8mb4_unicode_ci DEFAULT ''initiated'',
  `reject_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `uk_report_number` (`report_number`),
  KEY `idx_student` (`student_id`),
  KEY `idx_special_lab` (`special_lab_id`),
  KEY `idx_sdg_goal` (`sdg_goal_id`),
  KEY `fk_report_tracker` (`tracker_id`),
  CONSTRAINT `fk_report_tracker` FOREIGN KEY (`tracker_id`) REFERENCES `internship_tracker` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_report_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_report_special_lab` FOREIGN KEY (`special_lab_id`) REFERENCES `special_labs` (`id`),
  CONSTRAINT `fk_report_sdg` FOREIGN KEY (`sdg_goal_id`) REFERENCES `sdg_goals` (`id`),
  CONSTRAINT `fk_tracker` FOREIGN KEY (`tracker_id`) REFERENCES `internship_tracker` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=150001'

'CREATE TABLE `patent_tracker` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tracker_number` bigint unsigned DEFAULT NULL,
  `student_id` int NOT NULL,
  `patent_contribution` enum(''Applicant'',''Inventor'') NOT NULL,
  `second_student_id` int DEFAULT NULL,
  `third_student_id` int DEFAULT NULL,
  `fourth_student_id` int DEFAULT NULL,
  `fifth_student_id` int DEFAULT NULL,
  `sixth_student_id` int DEFAULT NULL,
  `seventh_student_id` int DEFAULT NULL,
  `eighth_student_id` int DEFAULT NULL,
  `ninth_student_id` int DEFAULT NULL,
  `tenth_student_id` int DEFAULT NULL,
  `patent_title` varchar(255) NOT NULL,
  `applicants_involved` enum(''BIT students only'',''BIT student along with faculty'',''BIT student along with external institutions'') NOT NULL,
  `faculty_id` varchar(50) DEFAULT NULL,
  `patent_type` enum(''Product/Process'',''Design'') NOT NULL,
  `has_image_layout_support` enum(''Yes'',''No'') DEFAULT ''No'',
  `experimentation_file_path` varchar(512) DEFAULT NULL,
  `has_formatted_drawings` enum(''Yes'',''No'') DEFAULT ''No'',
  `drawings_file_path` varchar(512) DEFAULT NULL,
  `forms_1_and_2_prepared` enum(''Yes'',''No'') DEFAULT ''No'',
  `forms_file_path` varchar(512) DEFAULT NULL,
  `iqac_verification` enum(''Initiated'',''Approved'',''Declined'') DEFAULT ''Initiated'',
  `reject_reason` varchar(255) DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_student_main` (`student_id`),
  KEY `fk_student_2` (`second_student_id`),
  KEY `fk_student_3` (`third_student_id`),
  KEY `fk_student_4` (`fourth_student_id`),
  KEY `fk_student_5` (`fifth_student_id`),
  KEY `fk_student_6` (`sixth_student_id`),
  KEY `fk_student_7` (`seventh_student_id`),
  KEY `fk_student_8` (`eighth_student_id`),
  KEY `fk_student_9` (`ninth_student_id`),
  KEY `fk_student_10` (`tenth_student_id`),
  KEY `fk_faculty` (`faculty_id`),
  CONSTRAINT `fk_student_main` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_2` FOREIGN KEY (`second_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_3` FOREIGN KEY (`third_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_4` FOREIGN KEY (`fourth_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_5` FOREIGN KEY (`fifth_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_6` FOREIGN KEY (`sixth_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_7` FOREIGN KEY (`seventh_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_8` FOREIGN KEY (`eighth_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_9` FOREIGN KEY (`ninth_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_student_10` FOREIGN KEY (`tenth_student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `faculty` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001'

'CREATE TABLE `patent_report` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int NOT NULL,
  `patent_status` enum(''filed'',''published'',''granted'') NOT NULL,
  `position_of_student` int DEFAULT NULL,
  `is_academic_project` tinyint(1) DEFAULT ''0'',
  `faculty_id_1` varchar(50) DEFAULT NULL,
  `faculty_id_2` varchar(50) DEFAULT NULL,
  `faculty_id_3` varchar(50) DEFAULT NULL,
  `faculty_id_4` varchar(50) DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `application_number` varchar(100) DEFAULT NULL,
  `sdg_goals_id` int DEFAULT NULL,
  `patent_tracker_id` int DEFAULT NULL,
  `level` enum(''national'',''international'') NOT NULL,
  `is_early_publication_filed` tinyint(1) DEFAULT NULL,
  `is_examination_filed` tinyint(1) DEFAULT NULL,
  `patent_license_details` text DEFAULT NULL,
  `funding_agency` varchar(255) DEFAULT NULL,
  `funds_received` tinyint(1) DEFAULT NULL,
  `fund_amount` decimal(12,2) DEFAULT NULL,
  `is_interdisciplinary` tinyint(1) DEFAULT NULL,
  `other_dept_name` varchar(100) DEFAULT NULL,
  `other_dept_student_count` int DEFAULT NULL,
  `approve_filed_by_bit_id_publication` int DEFAULT NULL,
  `approve_filed_by_bit_id_granted` int DEFAULT NULL,
  `yukti_proof_url` text DEFAULT NULL,
  `full_document_proof_url` text DEFAULT NULL,
  `cbr_receipt_url` text DEFAULT NULL,
  `publication_proof_url` text DEFAULT NULL,
  `granted_proof_url` text DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_student` (`student_id`),
  KEY `fk_faculty_1` (`faculty_id_1`),
  KEY `fk_faculty_2` (`faculty_id_2`),
  KEY `fk_faculty_3` (`faculty_id_3`),
  KEY `fk_faculty_4` (`faculty_id_4`),
  KEY `fk_sdg_goals` (`sdg_goals_id`),
  UNIQUE KEY `id` (`id`),
  CONSTRAINT `fk_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`),
  CONSTRAINT `fk_faculty_1` FOREIGN KEY (`faculty_id_1`) REFERENCES `faculty` (`id`),
  CONSTRAINT `fk_faculty_2` FOREIGN KEY (`faculty_id_2`) REFERENCES `faculty` (`id`),
  CONSTRAINT `fk_faculty_3` FOREIGN KEY (`faculty_id_3`) REFERENCES `faculty` (`id`),
  CONSTRAINT `fk_faculty_4` FOREIGN KEY (`faculty_id_4`) REFERENCES `faculty` (`id`),
  CONSTRAINT `fk_sdg_goals` FOREIGN KEY (`sdg_goals_id`) REFERENCES `sdg_goals` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin'