/**
 * Constants for Achievement Submission System
 */

// ============================================
// ACHIEVEMENT CATEGORIES
// ============================================

export const ACHIEVEMENT_CATEGORIES = [
  { id: 1, label: 'Newsletter Archive' },
  { id: 2, label: 'E-Content Developed' },
  { id: 3, label: 'Events Attended' },
  { id: 4, label: 'Events Organized' },
  { id: 5, label: 'External Examiner' },
  { id: 6, label: 'Faculty Journal Reviewer' },
  { id: 7, label: 'Guest Lecture Delivered' },
  { id: 8, label: 'International Visit' },
  { id: 9, label: 'Notable Achievement/Awards' },
  { id: 10, label: 'Paper Presentation' },
  { id: 11, label: 'Resource Person' },
  { id: 12, label: 'Online Course' },
] as const

// ============================================
// DEPARTMENTS
// ============================================

export const DEPARTMENTS = [
  'Aeronautical Engineering',
  'Agricultural Engineering',
  'Artificial Intelligence and Data Science',
  'Artificial Intelligence and Machine Learning',
  'Automobile Engineering',
  'Biomedical Engineering',
  'Biotechnology',
  'Chemistry',
  'Civil Engineering',
  'Computer Applications - CT',
  'Computer Science & Engineering',
  'Computer Science and Business Systems',
  'Computer Science and Design',
  'Computer Technology',
  'Dean Office',
  'Electrical and Electronics Engineering',
  'Electronics and Communication Engineering',
  'Electronics and Instrumentation Engineering',
  'Fashion Technology',
  'Food Technology',
  'General Engineering',
  'Humanities',
  'Industrial Safety Engineering',
  'Information Science and Engineering',
  'Information Technology',
  'Library',
  'Master of Business Applications',
  'Mathematics',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Physical Education',
  'Physics',
  'School of Management Studies',
  'Sports',
  'Technology Business Incubators',
  'Textile Technology',
  'Training and Placement',
  'Yoga',
] as const

// ============================================
// FACULTY LIST (900+ MEMBERS)
// ============================================

export const FACULTY_LIST = [
  'AARTHI N', 'ABDUL AZEEZ N', 'ABHIJEET KUMAR', 'ABHINANDH K A', 'ABHINAYA N',
  'ABHISHEK VATS', 'ABINAYA M', 'ABINAYA R', 'ABIRAMI A', 'ABIRAMI M',
  'ABISHA MARTIN', 'ABRAHAM BENJAMIN SAMUEL', 'ADHINARAYANAN B', 'AISHWARIYA M R', 'AISWARYA V',
  'AJAI A', 'AJAY B', 'AJIN R NAIR', 'AKALYADEVI K', 'AKSHAYA R',
  'ALAMELU M', 'ALEX STANLEY RAJA T', 'AMARKARTHIK A', 'AMIRTHAVALLI K', 'AMMU V',
  'ANAND A', 'ANANDAKUMAR K', 'ANANDAN P', 'ANANDHA BABU G', 'ANANDHA MOORTHY A',
  'ANANDHAKUMAR R', 'ANANTHA ESWARAN N', 'ANANTHAN S', 'ANANTHI D', 'ANANTHI P',
  'ANBAZHAKAN K', 'ANBURAJ M', 'ANDRIL ALAGUSABAI', 'ANITHA E', 'ANITHA R',
  'ANNAPOORANI B T', 'ANTONYRAJ J M', 'ANUGEETHA SHINE', 'ANUJA S', 'ANUPAMA RANI',
  'ANUSHA SELES S', 'ARAVINDHAN C', 'ARCHANA J', 'ARIFFA BEGUM S', 'ARIVU Y',
  'ARTHUR VASANTH J', 'ARULMANI S', 'ARULMURUGAN L', 'ARUN CHENDHURAN R', 'ARUN JAYAKAR S',
  'ARUN KUMAR D', 'ARUN KUMAR R', 'ARUN SHALIN L V', 'ARUNASREE TNA', 'ASHFORN HERMINA J M',
  'ASHOK J', 'ASHOK KUMAR A', 'ASHOKAN S', 'ASHOKKUMAR R', 'ASHRA SINDHIKKAA M',
  'ASHWATHI R', 'ASHWIN RAJ S', 'ASLIN JERUSHA D', 'ASWIN JAYA SURYA M J', 'ATHIRA AJITH',
  'ATHIRAJA A', 'BALAGANESH P', 'BALAJI M', 'BALAJI S', 'BALAKRISHNAN K',
  'BALAKRISHNARAJA R', 'BALAMURUGAN E', 'BALAMURUGAN R', 'BALAMURUGAN V T', 'BALASAMY K',
  'BALAVIGNESH S', 'BARANIDHARAN V', 'BASILEA CATHERINE J', 'BASKARAN P', 'BAZILA BANU A',
  'BENITA GRACIA THANGAM J', 'BHARANI KUMAR R', 'BHARANI N', 'BHARANI PRIYA A', 'BHARATH KUMAR T',
  'BHARATHI A', 'BHARATHIRAJA M', 'BHUVANESH N', 'BHUVANESWARI S', 'BIJU J',
  'BINDHU J', 'BOOPATHI C', 'BOOPATHIRAJA K P', 'BUVANESH P', 'CAROLINE CYNTHIA P',
  'CAROLINE VINNETIA S', 'CHANDRAMOHAN N', 'CHANDRAPRABHA K', 'CHANDRASEKARAN M', 'CHANDRU K S',
  'CHELLADURAI V', 'CHINNADURRAI CL', 'CHITRADEVI T N', 'CHOZHARAJAN P', 'DANIEL MADAN RAJA S',
  'DANIEL RAJ A', 'DAPHNE MEDONA J', 'DAVID WINSTER PRAVEENRAJ D', 'DEEPA D', 'DEEPA PRIYA B S',
  'DEEPA R', 'DEEPA SUMATHI M', 'DEEPA UNNIKRISHNAN', 'DEEPAK O P', 'DEEPANKUMAR S',
  'DEEPHA V', 'DEEPIKA J', 'DEEPIKA R', 'DHANABALU S N', 'DHANALAKSHMI S',
  'DHANAPAL V', 'DHANAPRIYA G', 'DHANASEKAR R', 'DHANDAPANI N', 'DHARANI S',
  'DHAVA PERUMAL C', 'DHAYANEETHI S', 'DHEEPANCHAKKRAVARTHY A', 'DHINESH S K', 'DHIVYA DHARSHINI U',
  'DHIVYA K T', 'DHIVYA P', 'DHIVYABHARATHI S', 'DINESH D', 'DINESH KUMAR L',
  'DINESH P S', 'DIVAKAR R', 'DIVYA P', 'DIVYA S', 'DIVYABARATHI P',
  'DURGADEVI S', 'EASUBATHAM ARMSTRONG ANAND J', 'EDAMAKANTI RAMANJI REDDY', 'ELANGO S', 'ELAVARASI T',
  'ESAKKI MADURA E', 'ESWARAMOORTHY V', 'EUGENE BERNA I', 'EZHIL G', 'EZHIL R',
  'FREDDY CHRIS M', 'GANAGAVALLI K', 'GANESH BABU C', 'GAYATHIRI B', 'GAYATHIRI DEVI S',
  'GAYATHIRI N R', 'GAYATHRI D', 'GAYATHRI G M', 'GAYATHRI K', 'GAYATHRI PRIYADARSHINI R',
  'GAYATHRI R', 'GAYATHRI S', 'GAYATHRIDEVI M', 'GAYATRI A', 'GEETHAMANI R',
  'GNANAPRAKASH V', 'GNANASUNDAR V M', 'GOKUL K', 'GOKUL L S', 'GOKUL M S',
  'GOKULNATH B V', 'GOLDVIN SUGIRTHA DHAS B', 'GOMATHI M', 'GOMATHI R', 'GOPAL R',
  'GOPALAKRISHNAN B', 'GOPALAKRISHNAN M', 'GOPI G', 'GOPIKA N P', 'GOPIKA RAM P',
  'GOWRI SHANKAR M', 'GOWRISHANKAR L', 'GOWTHAM RAJ G', 'GOWTHAMI P', 'GOWTHAMI S',
  'GUNALAN K', 'GUNASEKARAN M', 'GUNAVARDINI V', 'GURU VIMAL KUMAR M', 'HANUMANTH RAMJI K S',
  'HARI BALAJI M', 'HARI PRIYA R', 'HARI PRIYA T', 'HARIKUMAR R', 'HARIPRASAD V',
  'HARIPRIYA K K', 'HARISH KUMAAR P', 'HARITHA J', 'HARWINDER SINGH', 'HEMA PRIYA D',
  'HEMALATHA B', 'HEMALATHA K', 'IKRAM N', 'INDHU BHASHINI V', 'INDHUMATHI K',
  'INDIRANI A', 'INDIRANI C', 'INDU RANI B', 'JACKSON J', 'JANAGI R',
  'JANANI G', 'JANANI T', 'JANARTHANAN M', 'JAYA BRINDHA G', 'JAYA K',
  'JAYAKUMAR K', 'JAYAKUMAR N', 'JAYANTHI V', 'JAYARAMAN A', 'JAYASANKARI J S',
  'JAYASUDHA S', 'JEEVANANTHAM V', 'JEEVITHA G R', 'JEEVITHA S V', 'JEGADHEESWARAN S',
  'JESIN BENETO A', 'JEYANTH B', 'JEYARAMAN R', 'JEYAUTHMIGHA R K', 'JEYAVEL KARTHICK P',
  'JISHIN JAYAN T', 'JOHN CLEMENT SUNDER A', 'JONATHAN CARUN JAYASECARAN', 'JOSEPH SILVESTER K', 'JOTHIMANI S',
  'JYOTI V JETHE', 'KALAISELVAN S', 'KALAIVANI E', 'KALAIVANI R', 'KALAIYARASI M',
  'KALIDASAN B', 'KALIL RAHIMAN M', 'KALIMUTHU M', 'KALPANA R', 'KAMAL BASHA K',
  'KAMALA SHARADHA R', 'KAMALI D', 'KAMALRAJ D', 'KAMATCHI KANNAN V', 'KANCHANADEVI P',
  'KANIMOZHI A', 'KANIMOZHI T', 'KANNAN K P', 'KANTHIMATHI N', 'KARTHICK K N',
  'KARTHICK P', 'KARTHIGA SHENBAGAM N', 'KARTHIGA M', 'KARTHIK S', 'KARTHIKA M',
  'KARTHIKA M S', 'KARTHIKA S', 'KARTHIKAMANI R', 'KARTHIKEYAN G', 'KARTHIKEYAN S',
  'KARUNYAH AMIRTHADHARSHINI N', 'KARUPPUSAMY M', 'KARUPPUSAMY S', 'KASINIYA K', 'KASTHURI S',
  'KAVITHA A', 'KAVITHA C', 'KAVITHA R', 'KAVITHA S', 'KAVITHA V',
  'KAVIYAADHARSHANI D', 'KAVYA G S', 'KAYALVIZHI B', 'KEERTHANA K', 'KEERTHI S NAMBIAR',
  'KIRUPA SANKAR M', 'KIRUTHIGA R', 'KIRUTHIKA M', 'KIRUTHIKA S', 'KIRUTHIKA V R',
  'KODIESWARI A', 'KOTHAI A', 'KOUSHIK LAYEK', 'KRISHNA PRIYA G', 'KRISHNAKUMAR S',
  'KRISHNAMMAL N', 'KRISHNAMOORTHY V', 'KRISHNARAJ R', 'KUMAR R', 'KUMARESAN G',
  'KUMARESAN K', 'KUMARESAN T', 'LAKSHMANAN D', 'LAKSHMANAPRAKASH S', 'LAKSHMI NARAYANA M MOHAN',
  'LATHA S', 'LAVANYA C', 'LEEBAN MOSES M', 'LEELAVATHI R', 'LIKHIL GOPALAN',
  'LIMSA S', 'LINO L', 'LOGANAYAGAN S', 'LOGESWARI S', 'LOKESWARI P',
  'LUBNA YASMEEN R', 'MADHESWARAN S', 'MADHUMATHI S', 'MADHUMITHA A', 'MADHUMITHA J',
  'MAGESH KUMAR B', 'MAGESWARAN J', 'MAHESH KUMAR S', 'MAHESH S', 'MAHESHKUMAR K',
  'MAHESWARI K T', 'MAHIMA P', 'MAHUDESWARAN A', 'MALATHI BALASUBRAMANIYAN', 'MALATHI M',
  'MALATHI MAHALINGAM', 'MALATHI T', 'MANIGANDAN S', 'MANIMEGALAI S', 'MANISHA G',
  'MANIVANNAN C', 'MANIVANNAN S', 'MANJU M', 'MANJUNATH N V', 'MANOCHITRA A S',
  'MANOJKUMAR P', 'MANONMANI S', 'MANORANJITHAM R', 'MANU RAJU', 'MARAGATHAM D S',
  'MARIAAMUTHA R', 'MATHANKUMAR P', 'MATHISELVAN G', 'MATHU PRIYA J', 'MEENAKSHI DHANALAKSHMI M',
  'MEGALINGAM @ MURUGAN A', 'MEGAVARTHINI K K', 'MEKALA N', 'MEKALA R', 'MENAHA R',
  'MERCY P', 'MILINTHA MARY T P', 'MOHAMED IRSATH M', 'MOHAMED ISMAIL A', 'MOHAMMED ABUBACKER SIDDIQ A',
  'MOHAN BHARATHI C', 'MOHAN KUMAR V', 'MOHANAMBAL K', 'MOHANAPRIYA K', 'MOHANAPRIYA V',
  'MOHANRAJ A', 'MOHEMMED YOUSUF', 'MOUNIKA S', 'MUNEESWARI ALIAS SURYA S', 'MUNIRATHINAM T',
  'MURALI KRISHNAN M', 'MURUGAKANI S', 'MURUGAN K', 'MURUGAPPAN S', 'MURUGESAN P',
  'MUTHU KUMAR T', 'MUTHUKUMAR K', 'MUTHUKUMAR P', 'MUTHUKUMARAVEL K', 'MUTHUMEENA S',
  'MYTHILI G M', 'MYTHILI S', 'NAGAMANI T', 'NAGARAJAN P', 'NAGARAJAN S',
  'NALIFABEGAM J', 'NANDAGOPAL M', 'NANDAKUMAR K', 'NANDHAGOPAL M', 'NANDHAKUMAR A',
  'NANDHINI A P', 'NANDHINI B', 'NANDHINI K M', 'NANDHINI N', 'NANDHINI S S',
  'NARENDRA ILAYA PALLAVAN P', 'NARESH KUMAR M', 'NATARAJ N', 'NATARAJ R V', 'NAVANEETH KUMAR K',
  'NAVEEN GEORGE', 'NAVEEN P Y', 'NAVEEN R', 'NAVEEN SANKAR A', 'NAVEENA S',
  'NAVEENYA B P', 'NIJANDHAN K', 'NIKITHA M', 'NILAVU NIZA A', 'NIMKAR AMEY SANJAY',
  'NIRMAL KUMAR R', 'NIRMALA S', 'NIRMALADEVI J', 'NIRMALAKUMARI K', 'NIRMALAN R',
  'NISHA DEVI K', 'NISHANTHINI S', 'NISHANTHINI V', 'NITHIN P', 'NITHIYA PRIYA B T',
  'NITHYA BALA SUNDARI S', 'NITHYA G', 'NITHYA M', 'NITHYA R', 'NITHYA S',
  'NITHYANANTHAM S', 'NITHYAPRAKASH V', 'NITHYAPRIYA S', 'NIVEATHITHA S', 'NIVEDHA S',
  'NIVEDITA V S', 'NIVESH KUMAR K', 'NIVETHA G', 'NIVETHA R', 'NIVETHALAKSHMI S',
  'OORAPPAN G M', 'PAARIVALLAL RA', 'PACHAMUTHU P', 'PADMASHREE A', 'PALANISAMY A M',
  'PALANISAMY C', 'PANDIARAJ A', 'PANDIYAN M', 'PARASURAMAN P', 'PARIMALA M',
  'PARKAVI S', 'PARTHASARATHI P', 'PARVATHY V', 'PAVANADITYA BADIDA', 'PAVITHRA G',
  'PAVITHRA MKS', 'PAVITHRA R', 'PAVITHRA SHEN G T', 'PAWEL P', 'PAYAL DUTTA',
  'PAZHANIRAJA N', 'PERARASI T', 'PHILO SUMI', 'PIDATHALA SAHITYA', 'PONGALI SATHYA PRABU N',
  'PONMURUGAN M', 'PONNARMADHA S', 'PONNILA P', 'POOJA A S', 'POOJA HARI',
  'POOJITHA P', 'POOMANI K', 'POONGODI C', 'POORNIMA A', 'POORNIMASRE J',
  'POUSIA S', 'PRABAKAR S J', 'PRABAKARAN P', 'PRABANAND S C', 'PRABHA DEVI D',
  'PRABHAKARAN V', 'PRABHAVATHI K', 'PRABHU P S', 'PRABHU V', 'PRADEEP A D',
  'PRADEESH E L', 'PRAKASH E', 'PRAKASH K', 'PRAKASH K B', 'PRAKASH M',
  'PRAKASH S', 'PRAKASH S P', 'PRAMANIK R', 'PRASANTH A', 'PRASATH M S',
  'PRATHAP M R', 'PRATHEEBHA G', 'PRAVEEN KUMAR D', 'PRAVEEN S M', 'PRAVEEN V',
  'PRAVEENA R', 'PRAVIN M C', 'PRAVIN SAVARIDASS M', 'PREETHA R', 'PREETHA V',
  'PREETHAM SRIDAR S', 'PREETHI D', 'PREETHIMATHI L', 'PREMA R', 'PREMALATHA K',
  'PREMKUMAR C', 'PRIYA A', 'PRIYA J', 'PRIYA L', 'PRIYA R',
  'PRIYADARSHINI K', 'PRIYADHARSHINI M', 'PRIYADHARSHINI S', 'PRIYADHARSHNI S', 'PRIYADHARSINI A',
  'PRIYANGA M A', 'PRIYANKA B', 'PRIYANKA S', 'PUJAA SAKTHY M R K', 'PUNITHA V',
  'PURUSOTHAMAN P', 'PUSHPAVALLI M', 'QUALITHA BEGUM Z', 'RAGAMATHI S', 'RAGAVI M',
  'RAGHAVENDRA PRABHU S', 'RAGHUL S', 'RAGHUNATH M', 'RAGHURAMAN S', 'RAGUNATH D',
  'RAJ KUMAR V S', 'RAJA SEKAR K', 'RAJA SEKAR S', 'RAJA T', 'RAJAKUMAR K',
  'RAJAKUMAR P', 'RAJALASHMI K', 'RAJANAND KUMAR R', 'RAJASEETHARAMA S', 'RAJASEKAR L',
  'RAJASEKAR S S', 'RAJENDRAN M', 'RAJESH KANNA P', 'RAJESH KUMAR S', 'RAJESH T',
  'RAJESHKUMAR G', 'RAJIEV R', 'RAJKUMAR M', 'RAJU C', 'RAMACHANDRA RAJU K',
  'RAMAKRISHNAN A', 'RAMASAMI S', 'RAMESH C', 'RAMESH KUMAR T', 'RAMESH M',
  'RAMESH R', 'RAMESHKUMAR A', 'RAMESWARI R', 'RAMKUMAR R', 'RAMYA E',
  'RAMYA K', 'RAMYA M', 'RAMYA P', 'RAMYA R', 'RAMYA R S',
  'RANGANATHAN A', 'RANGARAJ K', 'RANJITH G', 'RANJITHAM M', 'RASHEEDHA A',
  'RATHNA S', 'RAVI KUMAR M', 'RAVIKUMAR R', 'REENA CATHERINE J', 'RENUGA DEVI S',
  'RENUKA K', 'RENUKA P', 'RESHMI T S', 'REVATHI V M', 'RISHIKESH N',
  'ROHINI D', 'ROHINI P', 'RUPASHINI P R', 'SAAHINA S', 'SABARMATHI K R',
  'SABEENA BEGAM S', 'SADASIVAM K', 'SADHASIVAM N', 'SAGUNTHALA DEVI P', 'SAJAN P PHILIP',
  'SAKTHI SURIYA RAJ J S', 'SAKTHISHARMILA P', 'SAKTHISHOBANA K', 'SAKTHIVEL MURUGAN E', 'SAKTHIYA RAM S',
  'SAMPOORNAM K P', 'SAMSONRAJ C', 'SAMYUKTHA V', 'SANCHITA MUKHERJEE', 'SANDHIYADEVI P',
  'SANDHYARANI R', 'SANGARAVADIVEL P', 'SANGAVI N', 'SANGEETHA K', 'SANGEETHA R',
  'SANGEETHAA SN', 'SANJOY DEB', 'SANKARANANTH S', 'SANNASI CHAKRAVARTHY S R', 'SANTHIYA B',
  'SANTHOSH KUMAR E', 'SANTHOSH KUMAR K V', 'SANTHOSH KUMAR S', 'SANTHOSH N', 'SARAH HELAN SATHYA A',
  'SARAN KUMAR A', 'SARANGAN K', 'SARANYA D', 'SARANYA D V', 'SARANYA K',
  'SARANYA M K', 'SARANYA N', 'SARANYA S', 'SARASWATHI C', 'SARATHKUMAR S R',
  'SARAVANA KUMAR R', 'SARAVANA MOORTHI P', 'SARAVANAKUMAR K', 'SARAVANAKUMAR P', 'SARAVANAKUMAR R',
  'SARAVANAN B', 'SARAVANAN K', 'SARAVANAN S', 'SARULATHA R', 'SASIKALA D',
  'SASIKUMAR C', 'SASITHRA S', 'SASSON TAFFWIN MOSES S', 'SATHEESH KUMAR T', 'SATHEESH N P',
  'SATHEESHKUMAR S', 'SATHESHKUMAR K', 'SATHIS KUMAR K', 'SATHISH KUMAR G', 'SATHISH KUMAR R',
  'SATHISH S', 'SATHISH V', 'SATHISHKANNAN R', 'SATHISHKUMAR C', 'SATHISHKUMAR P',
  'SATHISHKUMAR S', 'SATHIYA B', 'SATHIYAMURTHI P', 'SATHIYANARAYANAN T', 'SATHYAKUMAR N',
  'SATHYAMOORTHY J', 'SATHYARAJ S', 'SAVEETHA R', 'SELVABHARATHI P', 'SELVAKUMAR K',
  'SELVAKUMAR M', 'SELVAMUTHUKUMARAN D', 'SELVI S', 'SENGOTTUVELAN M', 'SENTHAMARAI M',
  'SENTHIL K', 'SENTHIL KUMAR J', 'SENTHIL KUMAR K L', 'SENTHIL KUMAR N', 'SENTHIL T',
  'SENTHILKUMAR G', 'SENTHILKUMAR P', 'SENTHILNATHAN S', 'SHANGARA NARAYANEE N P', 'SHANKAR N',
  'SHANKARI V', 'SHANMUGA PRAKASH R', 'SHANMUGA PRIYA R', 'SHANMUGA SUNDARI I', 'SHANMUGAPRIYA V',
  'SHARMILA A', 'SHARON CHRIS HEPZEBAH P', 'SHINY JENNIFER R', 'SHOBANA K B', 'SHOBIKA S T',
  'SHOUKATH ALI K', 'SHREE LALEITHA G', 'SHRI THARANYAA J P', 'SHUBHAM JOSHI', 'SHYAMALAPRASANNA A',
  'SHYAMSUNDAR S', 'SIBI JOHN A', 'SIDDHARTHAN B', 'SINDHUJA S', 'SINDHUJAA N',
  'SINDUJA M E', 'SISILI T', 'SIVA G', 'SIVABALAKRISHNAN R', 'SIVAKUMAR K',
  'SIVARAHINI K', 'SIVARAJ G', 'SIVARAMAN P', 'SNEHA B J', 'SNEHA K',
  'SNEKHA A R', 'SOBIYAA P', 'SOLANKE KRISHNA RUSTUMRAO', 'SOMASUNDARAM K', 'SOUNDARA B',
  'SOUNDARIYA R S', 'SOUNDARYA B', 'SOUNDRAPANDIAN E', 'SOWMMIYA S', 'SOWMYA C M',
  'SOWMYA P', 'SOWMYHA S', 'SREENIVEATHA P', 'SRI VIGNA HEMA V', 'SRI VINITHA V',
  'SRINITYA G', 'SRINIVASAN M', 'SRIPRIYANKA S', 'SRIRAM S', 'SRITHA P',
  'STEEPHAN AMALRAJ J', 'STEPHEN SAGAYARAJ A', 'SUBBULAKSHMI M', 'SUBHAPRIYA P', 'SUBHARATHNA N',
  'SUBHASHREE P', 'SUBRAJA T', 'SUBRAMANIAN K', 'SUBRAMANIYAN C', 'SUBRATA DAS',
  'SUDEV DUTTA', 'SUDHA R', 'SUDHA T', 'SUDHAHAR S', 'SUDHEER KHAN S',
  'SUDHIR KUMAR V', 'SUGANESH S', 'SUGANYA DEVI C R', 'SUGANYA G', 'SUGANYA K S',
  'SUGUNA R', 'SUJITHRA S', 'SUNDAR RAJ M', 'SUNDAR S', 'SUNDARA MURTHY S',
  'SUNDARAM S', 'SUNDARAMAHALINGAM A', 'SUNDARRAJU G', 'SUPRIYA U', 'SURESH CHALUVADI',
  'SURESH G', 'SURESH KUMAR J', 'SURESH N S', 'SURESH R', 'SURESHKUMAR M',
  'SURESHKUMAR S', 'SURIYA V', 'SUSEELA D', 'SUSEENDRAN S', 'SUVETHA C',
  'SWATHI G', 'SWATHYPRIYADHARSINI P', 'SWEETY PRASANNA KIRUBA G', 'SYAMA R', 'SYED ALTHAF S',
  'TAJDEEN A', 'TAMILARASAN V D', 'TAMILARASI R', 'TAMILSELVAN A', 'TAMILSELVAN S',
  'TAMILSELVI P', 'TAMILSELVI S', 'TAMILTHENDRAL M', 'THAMARAI SELVAN V', 'THAMILARASAN P',
  'THANGA PARVATHI B', 'THANGATAMILSELVIS S', 'THAPASYA PANKAJ', 'THARSANEE R M', 'THIRUMOORTHY M',
  'THIRUMURUGAN V', 'THULASIMANI T', 'UDAYKUMAR BABUBHAI ACHARYA', 'UMA MAHESWARI S', 'UMAMAGESWARI D',
  'UMAMAHESWARI M', 'USHA K S', 'UVARAJA V C', 'VAANATHI S', 'VADIVEL VIVEK V',
  'VADIVELU P', 'VAIDEESWARAN V', 'VAIDHYANATHAN B', 'VAIRAVEL K S', 'VAISHNAVI M',
  'VAISHNAVI N', 'VANEESWARI N', 'VANITHA K', 'VARSHA JOSEPHINE V', 'VASUDEVAN M',
  'VEERAKUMAR S', 'VELLINGIRI A', 'VELMURUGAN S', 'VELNATH R', 'VENKATESAN R',
  'VENKATESHKUMAR U', 'VIDHYA K', 'VIDHYA S', 'VIGNESH KUMAR S', 'VIGNESH PRABU V',
  'VIGNESH S', 'VIGNESHWARAN S', 'VIJAY FRANKLIN J', 'VIJAYAKRISHNAN S', 'VIJAYAKUMAR V',
  'VIJAYAKUMAR V N', 'VIJAYANAND P S', 'VIMAL ARASAN A', 'VIMALRAJ V', 'VINIT KUMAR JAIN',
  'VINODHINI R T', 'VINOTH KUMAR J', 'VINOTH KUMAR N', 'VINOTH M', 'VINOTHINI B',
  'VINOTHINI V R', 'VINOTHKUMAR N', 'VINU KUMAR S M', 'VISHNU SAJAN', 'VISWANATHAN G',
  'VISWANATHAN V', 'VIVEK KUMAR P', 'VIVEKANANDAN J', 'YAMUNA S', 'YUVALATHA S',
  'YUVARAJ D', 'YUVARAJ K', 'NA'
] as const

// ============================================
// SHARED FORM OPTIONS
// ============================================

export const COMMON_OPTIONS = {
  YES_NO: [
    { label: 'Yes', value: 'Yes' },
    { label: 'No', value: 'No' },
  ],
  STUDENT_YEARS: [
    { label: '1st Year', value: '1st Year' },
    { label: '2nd Year', value: '2nd Year' },
    { label: '3rd Year', value: '3rd Year' },
    { label: '4th Year', value: '4th Year' },
  ],
} as const

// ============================================
// EVENTS ATTENDED CONSTANTS
// ============================================

export const EVENTS_ATTENDED_OPTIONS = {
  SPECIAL_LAB_NAMES: ['Lab 1', 'Lab 2', 'Lab 3', 'Lab 4', 'Lab 5'],
  EVENT_TYPES: ['Conference', 'Workshop', 'Seminar', 'Training', 'Webinar'],
  ORGANIZER_TYPES: ['BIT', 'Industry', 'Foreign Institute', 'Others', 'Institute'],
  EVENT_LEVELS: ['International', 'National', 'State', 'Local'],
  SECTORS: ['Private', 'Government', 'Non-Profit'],
  EVENT_MODES: ['Online', 'Offline', 'Hybrid'],
  DURATION_UNITS: ['MONTHS', 'WEEKS', 'HOURS', 'DAYS'],
  SPONSORSHIP_TYPES: ['Fully Sponsored', 'Partially Sponsored', 'Self-Sponsored'],
  EVENT_OUTCOMES: ['Certificate Received', 'Award/Recognition', 'Knowledge Gained', 'Networking'],
} as const

// ============================================
// EVENTS ORGANIZED CONSTANTS
// ============================================

export const EVENTS_ORGANIZED_OPTIONS = {
  ROLES: ['Convener', 'Co-Convener', 'Co-ordinator', 'Organizing Secretary'],
  EVENT_CATEGORIES: [
    'Awareness of Trends in Technology',
    'IPR',
    'Research Methodology',
    'Entrepreneurship',
    'Placement',
    'Technical Skill Development',
    'Life Skill',
    'Soft Skill',
    'Communication Skill',
  ],
  JOINTLY_ORGANIZED: ['None', 'Other institute in India', 'Foreign university', 'Industry', 'Technical society'],
  GUEST_INSTITUTION_TYPES: ['International', 'National (Within TamilNadu)', 'National (Outside TamilNadu)'],
} as const

// ============================================
// GUEST LECTURE CONSTANTS
// ============================================

export const GUEST_LECTURE_OPTIONS = {
  SPECIAL_LAB_NAMES: ['Lab 1', 'Lab 2', 'Lab 3', 'Lab 4', 'Lab 5'],
  EVENT_TYPES: [
    'Certification course',
    'Conference',
    'Faculty Exchange Programme',
    'FDP',
    'Guest Lecture',
    'One credit course',
    'School',
    'Seminar',
    'STTP',
    'Training',
    'Webinar',
    'Workshop',
    'Hands-on Training',
    'Value Added course'
  ],
  AUDIENCE_TYPES: ['Students', 'Faculty', 'Engineering Trainee', 'Others'],
  ORG_TYPES: ['BIT', 'Industry', 'Foreign Institute', 'Others', 'Institute'],
  EVENT_LEVELS: ['International', 'National', 'State', 'Local'],
} as const

// ============================================
// ONLINE COURSE CONSTANTS
// ============================================

export const ONLINE_COURSE_OPTIONS = {
  ORGANIZERS: ['Private', 'Government'],
  LEVELS: ['State', 'National', 'International'],
  DURATIONS: ['1 Week', '2 Weeks', '1 Month', '2 Months', '3 Months', '6 Months', '1 Year'],
  CATEGORIES: ['Proctored-Exam', 'Self-paced with final assessment', 'Self-paced without final assessment'],
  SPONSORSHIP_TYPES: ['SELF', 'BIT', 'Funding_Agency'],
  CLAIMED_FOR_OPTIONS: ['FAP', 'Competency', 'Not_Applicable'],
} as const

// ============================================
// PAPER PRESENTATION CONSTANTS
// ============================================

export const PAPER_PRESENTATION_OPTIONS = {
  EVENT_MODES: ['Online', 'Offline'],
  ORGANIZERS: ['BIT', 'Industry', 'Foreign Institute', 'Others', 'Institute'],
  LEVELS: ['International', 'National'],
  SPONSORSHIP: ['SELF', 'BIT', 'Funding agency', 'Others'],
} as const

// ============================================
// VALIDATION MESSAGES
// ============================================

export const VALIDATION_MESSAGES = {
  REQUIRED_FIELD: 'This field is required',
  INVALID_DATE: 'Please enter a valid date',
  INVALID_EMAIL: 'Please enter a valid email',
  FILE_TOO_LARGE: 'File size exceeds 10MB limit',
  INVALID_FILE_TYPE: 'Invalid file type',
} as const
